// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB08aAUn5P8r4K6IF4t6v_J81teCuxQsGQ',
    appId: '1:332927903377:web:b0ee43a63805487ebd8130',
    messagingSenderId: '332927903377',
    projectId: 'shots-studio-c3fc0',
    authDomain: 'shots-studio-c3fc0.firebaseapp.com',
    storageBucket: 'shots-studio-c3fc0.firebasestorage.app',
    measurementId: 'G-4R4J8Y5DDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiN1VZB8RHEsIbSdi0skY3jRllZWQQfs0',
    appId: '1:332927903377:android:1fb6e81f231af2bbbd8130',
    messagingSenderId: '332927903377',
    projectId: 'shots-studio-c3fc0',
    storageBucket: 'shots-studio-c3fc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCopiLyUmkaOg5ZkIr1nfkjSVfDS0hoxwI',
    appId: '1:332927903377:ios:e28f75c4f0dabfccbd8130',
    messagingSenderId: '332927903377',
    projectId: 'shots-studio-c3fc0',
    storageBucket: 'shots-studio-c3fc0.firebasestorage.app',
    iosBundleId: 'com.ansah.shotsStudio',
  );
}
